#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    uri-encoding: utf-8

#spring
spring:
  datasource:
    url: jdbc:mysql:///cazj?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
  aop:
    proxy-target-class: false
  activiti:    check-process-definitions: false

#log
logging:
  level:
    com.cazj: debug
 
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/cazj/*/*.xml

#page
db:
  page:
    pageSize: 10







